# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('code_language', models.TextField(max_length=30)),
                ('context', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.TextField(max_length=20)),
                ('number', models.TextField(max_length=1000)),
            ],
        ),
    ]
