# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(blank='True', max_length=100)),
                ('login_now', models.IntegerField(blank='True')),
                ('login_date', models.DateTimeField(auto_now=True)),
                ('last_id', models.TextField(blank='True', max_length=20)),
                ('last_pwd', models.TextField(blank='True', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
