# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0002_learning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning',
            name='image',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='number',
        ),
        migrations.AlterField(
            model_name='learning',
            name='context',
            field=models.TextField(max_length=4000),
        ),
    ]
