# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0002_auto_20181116_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank='True', max_length=20)),
                ('visit_lank', models.IntegerField(blank='True')),
                ('study_lank', models.TextField(blank='True', max_length=1000)),
                ('coding_lank', models.TextField(blank='True', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='login_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user_ip',
            field=models.TextField(max_length=100),
        ),
    ]
