# Generated by Django 2.1.7 on 2019-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0003_auto_20181116_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='coding_lank',
            field=models.TextField(blank='True', default='1_1_1_1_1_1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='study_lank',
            field=models.TextField(blank='True', default='1_1_1_1_1_1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='visit_lank',
            field=models.IntegerField(blank='True', default=1),
        ),
    ]
