# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0003_auto_20181024_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='code',
            field=models.TextField(default='Error', max_length=2000),
        ),
        migrations.AlterField(
            model_name='learning',
            name='context',
            field=models.TextField(default='Error', max_length=4000),
        ),
        migrations.AlterField(
            model_name='learning',
            name='title',
            field=models.TextField(default='Error', max_length=20),
        ),
    ]
